pretrained_model_path: ""
result_path: "./results"
training_log_rate: 10

model_arch: flownets
worker_threads: 8
epochs: 300
start_epoch: 0
epoch_size: 1000
batch_size: 8
div_flow: 20
shuffle_training_set: true
shuffle_validation_set: false

tensorboard:
  learning_rate:
    enable: true
    log_rate: 10
  weight_and_bias:
    enable: true
    log_rate: 1000
  gradient:
    enable: true
    log_rate: 1000
  sample_output:
    enable: true
    num_samples: 3

# Currently, only 'flying_chairs' is supported.
dataset:
  type: flying_chairs
  path: /hdd/data/optical_flow/freiburg/FlyingChairs/FlyingChairs_release/data

solver:
  type: adam
  alpha: 0.9
  beta: 0.999
  learning_rate: 0.0001
  weight_decay:
    scale: 0.5
    weight: 4e-4
    bias: 0
  milestones: [100, 150, 200]
  multiscale_weights: [0.005, 0.01, 0.02, 0.08, 0.32]

# ---------- Dataset options
flying_chairs:
  split_dataset: true
  read_split_file: false
  save_split_file: true
  split_file_read_path: ./resources/flying_chairs_split.txt
  split_ratio: 0.9
