pretrained_model_path: ""
result_path: "./results"
training_log_rate: 10

model_arch: flownets
worker_threads: 8
epochs: 300
start_epoch: 0
epoch_size: 1000
batch_size: 8
div_flow: 20
shuffle_training_set: false
shuffle_test_set: false

# Currently, only 'flying_chairs' is supported.
dataset:
  type: flying_chairs
  path: /hdd/data/optical_flow/freiburg/FlyingChairs/FlyingChairs_release/data

solver:
  type: adam
  alpha: 0.9
  beta: 0.999
  learning_rate: 0.0001
  learning_rate_decay: 0.5
  milestones: [100, 150, 200]
  weight_decay: 4e-4
  bias_decay: 0
  multiscale_weights: [0.005, 0.01, 0.02, 0.08, 0.32]

# ---------- Dataset options
flying_chairs:
  split_dataset: true
  read_split_file: false
  save_split_file: true
  split_file_read_path: ./resources/flying_chairs_split.txt
  split_ratio: 0.9
